MongoDB:
  URI: 'your.mongodb.uri'
General:
  Default-Kits:
    - 'PvP'
  Kit-To-Equip: "PvP"
  #Delay between each save (second)
  Save-Timer: 6000
  #Combat timer time (second)
  Combar-Timer: 20
  #Spawn timer time (second)
  Spawn-Timer: 8